version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: eco-ideas-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eco_ideas_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: